dist: trusty
sudo: required

language: go

addons:
  apt:
    packages:
    - realpath

before_install:
  - sudo add-apt-repository ppa:dqlite-maintainers/master -y
  - sudo apt-get update -q
  - sudo apt-get install libsqlite3-dev libuv1-dev libraft-dev libco-dev libdqlite-dev -y
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/tsenart/deadcode

script:
  - go get -t -tags libsqlite3 ./...
  - go vet -tags libsqlite3 ./...
  - golint
  - deadcode
  - project=github.com/canonical/go-dqlite
  - GO_RAFT_TEST_LATENCY=10.0 $GOPATH/bin/overalls -project $project -covermode=count -- -tags libsqlite3 -timeout 240s
  - $GOPATH/bin/goveralls -coverprofile overalls.coverprofile -service=travis-ci

go:
  - "1.11"
